<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            array(
                'name' =>  "Caramel Coffee with Chocolate",
                'price' => 59.9,
                'image' => "coffee_01",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Large Cold Coffee with Chocolate",
                'price' => 49.9,
                'image' => "coffee_02",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Large Cold Latte with Chocolate",
                'price' => 54.9,
                'image' => "coffee_03",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Large Cold Latte with Chocolate",
                'price' => 54.9,
                'image' => "coffee_04",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Large Cold Milkshake with Chocolate",
                'price' => 54.9,
                'image' => "coffee_05",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Small Hot Mocha Coffee",
                'price' => 39.9,
                'image' => "coffee_06",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Large Hot Mocha Coffee with Chocolate",
                'price' => 59.9,
                'image' => "coffee_07",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Large Hot Cappuccino Coffee",
                'price' => 59.9,
                'image' => "coffee_08",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Medium Hot Mocha Coffee",
                'price' => 49.9,
                'image' => "coffee_09",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Medium Cold Mocha Coffee with Caramel",
                'price' => 49.9,
                'image' => "coffee_10",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Medium Cold Mocha Coffee with Chocolate",
                'price' => 49.9,
                'image' => "coffee_11",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Espresso Coffee",
                'price' => 29.9,
                'image' => "coffee_12",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Large Caramel Cappuccino Coffee",
                'price' => 59.9,
                'image' => "coffee_13",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Large Caramel Coffee",
                'price' => 59.9,
                'image' => "coffee_14",
                'category_id' => 1,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 3 Chocolate Donuts",
                'price' => 39.9,
                'image' => "donuts_01",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 3 Glazed Donuts",
                'price' => 39.9,
                'image' => "donuts_02",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Strawberry Donut",
                'price' => 19.9,
                'image' => "donuts_03",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Donut with Chocolate Cookie",
                'price' => 19.9,
                'image' => "donuts_04",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Glazed Donut with Strawberry Sprinkles",
                'price' => 19.9,
                'image' => "donuts_05",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Glazed Donut with Chocolate",
                'price' => 19.9,
                'image' => "donuts_06",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Chocolate Donut with MORE Chocolate",
                'price' => 19.9,
                'image' => "donuts_07",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 3 Chocolate Donuts",
                'price' => 39.9,
                'image' => "donuts_08",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 3 Donuts with Vanilla and Chocolate",
                'price' => 39.9,
                'image' => "donuts_09",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 6 Donuts",
                'price' => 69.9,
                'image' => "donuts_10",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 3 Assorted Donuts",
                'price' => 39.9,
                'image' => "donuts_11",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Natural Donut with Chocolate",
                'price' => 19.9,
                'image' => "donuts_12",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 3 Chocolate Donuts with Sprinkles",
                'price' => 39.9,
                'image' => "donuts_13",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Chocolate and Coconut Donut",
                'price' => 19.9,
                'image' => "donuts_14",
                'category_id' => 4,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of Chocolate Cookies",
                'price' => 29.9,
                'image' => "cookies_01",
                'category_id' => 6,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of Chocolate and Oatmeal Cookies",
                'price' => 39.9,
                'image' => "cookies_02",
                'category_id' => 6,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of Vanilla Muffins",
                'price' => 39.9,
                'image' => "cookies_03",
                'category_id' => 6,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 4 Oatmeal Cookies",
                'price' => 24.9,
                'image' => "cookies_04",
                'category_id' => 6,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Assorted Butter Cookies",
                'price' => 39.9,
                'image' => "cookies_05",
                'category_id' => 6,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Fruit Flavored Cookies",
                'price' => 39.9,
                'image' => "cookies_06",
                'category_id' => 6,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Simple Burger",
                'price' => 59.9,
                'image' => "hamburgers_01",
                'category_id' => 2,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Chicken Burger",
                'price' => 59.9,
                'image' => "hamburgers_02",
                'category_id' => 2,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Chicken and Chili Burger",
                'price' => 59.9,
                'image' => "hamburgers_03",
                'category_id' => 2,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Cheese and Pickles Burger",
                'price' => 59.9,
                'image' => "hamburgers_04",
                'category_id' => 2,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Quarter Pounder Burger",
                'price' => 59.9,
                'image' => "hamburgers_05",
                'category_id' => 2,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Double Cheese Burger",
                'price' => 69.9,
                'image' => "hamburgers_06",
                'category_id' => 2,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Special Hot Dog",
                'price' => 49.9,
                'image' => "hamburgers_07",
                'category_id' => 2,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pack of 2 Hot Dogs",
                'price' => 69.9,
                'image' => "hamburgers_08",
                'category_id' => 2,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "4 Slices of Cheesecake",
                'price' => 69.9,
                'image' => "cake_01",
                'category_id' => 5,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Special Waffle",
                'price' => 49.9,
                'image' => "cake_02",
                'category_id' => 5,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "House Croissants",
                'price' => 39.9,
                'image' => "cake_03",
                'category_id' => 5,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Cheesecake",
                'price' => 19.9,
                'image' => "cake_04",
                'category_id' => 5,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Chocolate Cake",
                'price' => 29.9,
                'image' => "cake_05",
                'category_id' => 5,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Slice of Chocolate Cake",
                'price' => 29.9,
                'image' => "cake_06",
                'category_id' => 5,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Spicy Pizza with Double Cheese",
                'price' => 69.9,
                'image' => "pizzas_01",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Ham and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_02",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Double Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_03",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "House Special Pizza",
                'price' => 69.9,
                'image' => "pizzas_04",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Chorizo Pizza",
                'price' => 69.9,
                'image' => "pizzas_05",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Hawaiian Pizza",
                'price' => 69.9,
                'image' => "pizzas_06",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Bacon Pizza",
                'price' => 69.9,
                'image' => "pizzas_07",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Vegetable and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_08",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Pepperoni and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_09",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Olives and Cheese Pizza",
                'price' => 69.9,
                'image' => "pizzas_10",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'name' =>  "Cheese, Ham, and Mushroom Pizza",
                'price' => 69.9,
                'image' => "pizzas_11",
                'category_id' => 3,
                'stock' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ];

        DB::table('products')->insert($data);
    }
}
